server {
    listen 80;
    server_name localhost;

    location /dicom-web/ {
        proxy_pass http://orthanc:8042;
        proxy_set_header Host $host;
        proxy_request_buffering off;
        client_max_body_size 512m;
    }

    location / {
        proxy_pass http://ohif:80;
        proxy_set_header Host $host;
    }
}
